# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list. 



Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
np.__version__

'1.26.4'

#### 3. Create a null vector of size 10 (★☆☆)

In [5]:
arr=np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [7]:
arr=np.arange(0,20,4)
print(arr.size)

5


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [8]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retai

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [9]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [11]:
arr=np.arange(10,50)
print(arr)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [12]:
print(arr[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [13]:
arr=np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [18]:
l=[1,2,0,0,4,0]
arr=np.array(l)
#non zero elements
arr=arr[np.nonzero(arr)]
l=arr[arr!=0]
print(l)

[1 2 4]


#### 11. Create a 3x3 identity matrix (★☆☆)

In [20]:
arr=np.eye(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [23]:
arr=np.random.rand(3,3,3)
arr

array([[[0.92245267, 0.86413444, 0.16331939],
        [0.94759273, 0.13739184, 0.43165687],
        [0.96585846, 0.32989901, 0.11100392]],

       [[0.65327045, 0.04562913, 0.78703138],
        [0.6504716 , 0.52213578, 0.16958966],
        [0.21718995, 0.96627413, 0.06412821]],

       [[0.40514573, 0.11548998, 0.72246706],
        [0.0789726 , 0.71776188, 0.10511141],
        [0.0533147 , 0.76653757, 0.04516467]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [26]:
arr=np.random.randint(1,100,(10,10))
print(np.max(arr))
print(np.min(arr))
      

98
1


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [29]:
arr=np.random.randint(1,50,(30))
print(arr.mean())

22.8


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [31]:
arr=np.ones((5,5),dtype=int)
arr[1:-1,1:-1]=0
arr

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [35]:
arr=np.arange(9).reshape(3,3)
padded_array=np.pad(arr,pad_width=3,mode='constant',constant_values=0)
padded_array

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 2, 0, 0, 0],
       [0, 0, 0, 3, 4, 5, 0, 0, 0],
       [0, 0, 0, 6, 7, 8, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [2]:
matrix = np.zeros((5, 5), dtype=int)
np.fill_diagonal(matrix[1:], [1, 2, 3, 4])
print(matrix)


[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [4]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [4]:
shape = (6, 7, 8)
element_index = 99
x = element_index // (shape[1] * shape[2])
y = (element_index % (shape[1] * shape[2])) // shape[2]
z = (element_index % (shape[1] * shape[2])) % shape[2]
print(f"Index of 100th element: ({x}, {y}, {z})")

Index of 100th element: (1, 5, 3)


#21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [5]:
pattern = np.array([[0, 1], [1, 0]])
checkerboard = np.tile(pattern, (4, 4))
print(checkerboard)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [6]:
matrix = np.random.rand(5, 5)
normalized_matrix = (matrix - np.min(matrix)) / (np.max(matrix) - np.min(matrix))
print("Original Matrix:\n", matrix)
print("\nNormalized Matrix:\n", normalized_matrix)

Original Matrix:
 [[0.77413822 0.7362615  0.66482845 0.92045258 0.83748349]
 [0.6126123  0.17177353 0.03760356 0.85363338 0.14356493]
 [0.60566947 0.12274668 0.69892954 0.80039316 0.11283374]
 [0.84177397 0.36164    0.98322372 0.80400158 0.93381556]
 [0.7121748  0.89102895 0.3538713  0.39715519 0.63711545]]

Normalized Matrix:
 [[0.77889061 0.73883571 0.66329476 0.93361908 0.84587868]
 [0.60807581 0.1418857  0.         0.86295731 0.1120549 ]
 [0.60073371 0.09003946 0.6993569  0.80665539 0.07955645]
 [0.85041589 0.34267083 1.         0.81047133 0.94775053]
 [0.71336386 0.90250338 0.33445537 0.38022839 0.63398806]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [7]:
rgba_dtype = np.dtype([('R', np.uint8), ('G', np.uint8), ('B', np.uint8), ('A', np.uint8)])
color = np.array((255, 127, 80, 255), dtype=rgba_dtype)
print("Custom RGBA dtype:", rgba_dtype)
print("Example RGBA color:", color)

Custom RGBA dtype: [('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')]
Example RGBA color: (255, 127, 80, 255)


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [8]:
A = np.random.rand(5, 3)
B = np.random.rand(3, 2)
result = np.dot(A, B)
print("Matrix A (5x3):\n", A)
print("\nMatrix B (3x2):\n", B)
print("\nResulting Matrix (5x2):\n", result)


Matrix A (5x3):
 [[0.89838247 0.60782752 0.37605864]
 [0.08382634 0.88126419 0.91177671]
 [0.57443035 0.5340842  0.45745684]
 [0.38666653 0.15093412 0.94127635]
 [0.83041451 0.32282818 0.02802871]]

Matrix B (3x2):
 [[0.47209398 0.6916531 ]
 [0.3811076  0.42500196]
 [0.69265659 0.27652999]]

Resulting Matrix (5x2):
 [[0.91624814 0.9836884 ]
 [1.00697854 0.68465136]
 [0.79158915 0.7507939 ]
 [0.89204636 0.59187755]
 [0.53448023 0.71931216]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [10]:

arr = np.random.randint(0, 11, size=10) 
arr[(arr > 3) & (arr < 8)] *= -1
print("Modified Array:\n", arr)


Modified Array:
 [ 8 -4 10 -4  2  8 -4 -6 -4  8]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [11]:
# Author: Jake VanderPlas

print(sum(range(5), -1))
from numpy import *
print(sum(range(5), -1))


9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [9]:
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z


NameError: name 'Z' is not defined

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [12]:
import numpy as np

print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))


nan
0
[-2.14748365e+09]


C:\Users\kt003\AppData\Local\Temp\ipykernel_18608\486419588.py:3: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
C:\Users\kt003\AppData\Local\Temp\ipykernel_18608\486419588.py:4: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
C:\Users\kt003\AppData\Local\Temp\ipykernel_18608\486419588.py:5: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ? (★☆☆)

In [13]:
arr = np.array([-1.5, -0.7, 0.2, 1.3, 2.8])
rounded = np.copysign(np.ceil(np.abs(arr)), arr)
print("Original array: ", arr)
print("Rounded away from zero: ", rounded)


Original array:  [-1.5 -0.7  0.2  1.3  2.8]
Rounded away from zero:  [-2. -1.  1.  2.  3.]


#### 30. How to find common values between two arrays? (★☆☆)

In [14]:

arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([3, 4, 5, 6, 7])

common_values = np.intersect1d(arr1, arr2)

print("Common values:", common_values)


Common values: [3 4 5]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
import numpy as np

# Ignore all floating-point warnings
np.seterr(all='ignore')

# Example operation that would normally raise a warning
print(np.array(0) / np.array(0))  # Normally produces a division by zero warning


#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [16]:

np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\kt003\AppData\Local\Temp\ipykernel_18608\4132845568.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [27]:
from datetime import datetime, timedelta

today = datetime.today()
yesterday = today - timedelta(days=1)

tomorrow = today + timedelta(days=1)

print("Yesterday:", yesterday.date())
print("Today:", today.date())
print("Tomorrow:", tomorrow.date())


Yesterday: 2025-03-31
Today: 2025-04-01
Tomorrow: 2025-04-02


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [25]:
import pandas as pd
july_2016 = pd.date_range('2016-07-01', '2016-07-31', freq='D')

print(july_2016)


DatetimeIndex(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
               '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
               '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
               '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
               '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
               '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
               '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
               '2016-07-29', '2016-07-30', '2016-07-31'],
              dtype='datetime64[ns]', freq='D')


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [26]:
import numpy as np

# Example arrays A and B
A = np.array([1, 2, 3, 4])
B = np.array([4, 3, 2, 1])

A += B 
A *= -0.5 * A 
print(A)


UFuncTypeError: Cannot cast ufunc 'multiply' output from dtype('float64') to dtype('int32') with casting rule 'same_kind'

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [22]:

arr = np.random.rand(5) * 10 
floor_result = np.floor(arr)
trunc_result = np.trunc(arr)
astype_result = arr.astype(int)

int_div_result = arr // 1

print("Original array:", arr)
print("Method 1 (np.floor):", floor_result)
print("Method 2 (np.trunc):", trunc_result)
print("Method 3 (astype(int)):", astype_result)
print("Method 4 (integer division // 1):", int_div_result)


Original array: [8.47080702 0.12957671 7.13718496 9.17615886 8.0352938 ]
Method 1 (np.floor): [8. 0. 7. 9. 8.]
Method 2 (np.trunc): [8. 0. 7. 9. 8.]
Method 3 (astype(int)): [8 0 7 9 8]
Method 4 (integer division // 1): [8. 0. 7. 9. 8.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [20]:

matrix = np.tile(np.arange(5), (5, 1))

print(matrix)


[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [19]:

def generate_integers():
    for i in range(10):
        yield i

generated_array = np.array(list(generate_integers()))

print(generated_array)


[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [18]:

vector = np.random.uniform(0, 1, 10)

print(vector)


[0.54474162 0.60464091 0.56169001 0.38689608 0.87974572 0.42285767
 0.418051   0.43063494 0.6556342  0.03439631]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [17]:

random_vector = np.random.rand(10)

sorted_vector = np.sort(random_vector)

print("Random vector:", random_vector)
print("Sorted vector:", sorted_vector)


Random vector: [0.89074446 0.44864702 0.65100699 0.78439109 0.14131562 0.88350868
 0.41239595 0.07306001 0.79429714 0.61998956]
Sorted vector: [0.07306001 0.14131562 0.41239595 0.44864702 0.61998956 0.65100699
 0.78439109 0.79429714 0.88350868 0.89074446]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [28]:

arr = np.array([1, 2, 3, 4, 5])
total = sum(arr)
print("Sum:", total)


Sum: 15


#### 42. Consider two random array A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

In [5]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

# Slow version
np.diag(np.dot(A, B))

# Fast version
np.sum(A * B.T, axis=1)

array([2.32737734, 0.80259229, 0.37604657, 1.06133105, 1.21103206])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)